/**
 * L3: the item catalogue.
 *
 * To add an item: add one entry here, add a sprite spec with the same `sprite`
 * id in sprites.ts, and put it in a loot table. Nothing above L3 changes.
 */

import type { ItemCatalog, ItemDef } from '@game/items';

const item = (def: ItemDef): ItemDef => def;

export const ITEMS: ItemCatalog = {
  'item.water': item({
    id: 'item.water',
    name: 'Water bottle',
    width: 1,
    height: 2,
    maxStack: 2,
    weight: 1,
    tags: ['drink'],
    sprite: 'item.water',
    use: { thirst: 46, consumed: true },
    damage: 1,
    noise: 60,
    throwable: true,
    charge: 0,
    description: 'Flat, warm, drinkable.',
  }),
  'item.soda': item({
    id: 'item.soda',
    name: 'Vending soda',
    width: 1,
    height: 1,
    maxStack: 4,
    weight: 0.5,
    tags: ['drink'],
    sprite: 'item.soda',
    use: { thirst: 24, hunger: 6, stamina: 12, consumed: true },
    damage: 1,
    noise: 80,
    throwable: true,
    charge: 0,
    description: 'Sugar and static.',
  }),
  'item.crackers': item({
    id: 'item.crackers',
    name: 'Cracker pack',
    width: 1,
    height: 1,
    maxStack: 5,
    weight: 0.25,
    tags: ['food'],
    sprite: 'item.crackers',
    use: { hunger: 28, thirst: -4, consumed: true },
    damage: 0,
    noise: 40,
    throwable: false,
    charge: 0,
    description: 'Dry enough to hurt.',
  }),
  'item.canned': item({
    id: 'item.canned',
    name: 'Canned meal',
    width: 2,
    height: 1,
    maxStack: 2,
    weight: 0.6,
    tags: ['food'],
    sprite: 'item.canned',
    use: { hunger: 52, thirst: -6, consumed: true },
    damage: 2,
    noise: 90,
    throwable: true,
    charge: 0,
    description: 'No label. Still sealed.',
  }),
  'item.medkit': item({
    id: 'item.medkit',
    name: 'First aid tin',
    width: 2,
    height: 2,
    maxStack: 1,
    weight: 1.2,
    tags: ['medical'],
    sprite: 'item.medkit',
    use: { health: 55, sanity: 6, consumed: true },
    damage: 1,
    noise: 70,
    throwable: false,
    charge: 0,
    description: 'Most of it is still inside.',
  }),
  'item.bandage': item({
    id: 'item.bandage',
    name: 'Gauze roll',
    width: 1,
    height: 1,
    maxStack: 4,
    weight: 0.2,
    tags: ['medical'],
    sprite: 'item.bandage',
    use: { health: 20, consumed: true },
    damage: 0,
    noise: 20,
    throwable: false,
    charge: 0,
    description: 'Stops the worst of it.',
  }),
  'item.flashlight': item({
    id: 'item.flashlight',
    name: 'Flashlight',
    width: 1,
    height: 2,
    maxStack: 1,
    weight: 0.6,
    tags: ['light'],
    sprite: 'item.flashlight',
    use: null,
    damage: 3,
    noise: 60,
    throwable: false,
    charge: 300,
    description: 'Hold it and switch it on.',
  }),
  'item.battery': item({
    id: 'item.battery',
    name: 'Battery',
    width: 1,
    height: 1,
    maxStack: 6,
    weight: 0.15,
    tags: ['battery'],
    sprite: 'item.battery',
    use: { charge: 240, consumed: true },
    damage: 0,
    noise: 30,
    throwable: false,
    charge: 0,
    description: 'Feeds the flashlight in hand.',
  }),
  'item.pipe': item({
    id: 'item.pipe',
    name: 'Steel pipe',
    width: 1,
    height: 3,
    maxStack: 1,
    weight: 2.2,
    tags: ['weapon'],
    sprite: 'item.pipe',
    use: null,
    damage: 34,
    noise: 200,
    throwable: true,
    charge: 0,
    description: 'Heavy, loud, better than nothing.',
  }),
  'item.wrench': item({
    id: 'item.wrench',
    name: 'Pipe wrench',
    width: 1,
    height: 2,
    maxStack: 1,
    weight: 1.4,
    tags: ['weapon'],
    sprite: 'item.wrench',
    use: null,
    damage: 24,
    noise: 170,
    throwable: true,
    charge: 0,
    description: 'Swings badly. Still swings.',
  }),
  'item.noisemaker': item({
    id: 'item.noisemaker',
    name: 'Wind-up clock',
    width: 1,
    height: 1,
    maxStack: 3,
    weight: 0.4,
    tags: ['lure'],
    sprite: 'item.noisemaker',
    use: null,
    damage: 0,
    noise: 460,
    throwable: true,
    charge: 0,
    description: 'Throw it. Then be somewhere else.',
  }),
};
