/**
 * L3: the item catalogue.
 *
 * To add an item: add one entry here, add a sprite spec with the same `sprite`
 * id in sprites.ts, and put it in a loot table. Nothing above L3 changes.
 */

import type { ItemCatalog, ItemDef } from '@game/items';
import { WEAPONS } from './tuning';

const item = (def: ItemDef): ItemDef => def;

export const ITEMS: ItemCatalog = {
  /**
   * Bare hands are an item like any other, so the combat module never needs a
   * special case for them. Never spawned, never carried — it is the stat block
   * a broken weapon and a non-weapon both fall back to.
   */
  'item.hands': item({
    id: 'item.hands',
    nameKey: 'item.item.hands.name',
    descriptionKey: 'item.item.hands.desc',
    width: 1,
    height: 1,
    maxStack: 1,
    weight: 0,
    tags: [],
    sprite: 'item.ground',
    use: null,
    melee: WEAPONS.hands,
    noise: 40,
    throwable: false,
    charge: 0,
  }),
  'item.water': item({
    id: 'item.water',
    nameKey: 'item.item.water.name',
    descriptionKey: 'item.item.water.desc',
    width: 1,
    height: 2,
    maxStack: 2,
    weight: 1,
    tags: ['drink'],
    sprite: 'item.water',
    use: { thirst: 46, consumed: true },
    melee: null,
    noise: 60,
    throwable: true,
    charge: 0,
  }),
  'item.soda': item({
    id: 'item.soda',
    nameKey: 'item.item.soda.name',
    descriptionKey: 'item.item.soda.desc',
    width: 1,
    height: 1,
    maxStack: 4,
    weight: 0.5,
    tags: ['drink'],
    sprite: 'item.soda',
    use: { thirst: 24, hunger: 6, stamina: 12, consumed: true },
    melee: null,
    noise: 80,
    throwable: true,
    charge: 0,
  }),
  'item.crackers': item({
    id: 'item.crackers',
    nameKey: 'item.item.crackers.name',
    descriptionKey: 'item.item.crackers.desc',
    width: 1,
    height: 1,
    maxStack: 5,
    weight: 0.25,
    tags: ['food'],
    sprite: 'item.crackers',
    use: { hunger: 28, thirst: -4, consumed: true },
    melee: null,
    noise: 40,
    throwable: false,
    charge: 0,
  }),
  'item.canned': item({
    id: 'item.canned',
    nameKey: 'item.item.canned.name',
    descriptionKey: 'item.item.canned.desc',
    width: 2,
    height: 1,
    maxStack: 2,
    weight: 0.6,
    tags: ['food'],
    sprite: 'item.canned',
    use: { hunger: 52, thirst: -6, consumed: true },
    melee: null,
    noise: 90,
    throwable: true,
    charge: 0,
  }),
  'item.medkit': item({
    id: 'item.medkit',
    nameKey: 'item.item.medkit.name',
    descriptionKey: 'item.item.medkit.desc',
    width: 2,
    height: 2,
    maxStack: 1,
    weight: 1.2,
    tags: ['medical'],
    sprite: 'item.medkit',
    use: { health: 55, sanity: 6, consumed: true },
    melee: null,
    noise: 70,
    throwable: false,
    charge: 0,
  }),
  'item.bandage': item({
    id: 'item.bandage',
    nameKey: 'item.item.bandage.name',
    descriptionKey: 'item.item.bandage.desc',
    width: 1,
    height: 1,
    maxStack: 4,
    weight: 0.2,
    tags: ['medical'],
    sprite: 'item.bandage',
    use: { health: 20, consumed: true },
    melee: null,
    noise: 20,
    throwable: false,
    charge: 0,
  }),
  'item.flashlight': item({
    id: 'item.flashlight',
    nameKey: 'item.item.flashlight.name',
    descriptionKey: 'item.item.flashlight.desc',
    width: 1,
    height: 2,
    maxStack: 1,
    weight: 0.6,
    tags: ['light'],
    sprite: 'item.flashlight',
    use: null,
    melee: null,
    noise: 60,
    throwable: false,
    charge: 300,
  }),
  'item.battery': item({
    id: 'item.battery',
    nameKey: 'item.item.battery.name',
    descriptionKey: 'item.item.battery.desc',
    width: 1,
    height: 1,
    maxStack: 6,
    weight: 0.15,
    tags: ['battery'],
    sprite: 'item.battery',
    use: { charge: 240, consumed: true },
    melee: null,
    noise: 30,
    throwable: false,
    charge: 0,
  }),
  'item.pipe': item({
    id: 'item.pipe',
    nameKey: 'item.item.pipe.name',
    descriptionKey: 'item.item.pipe.desc',
    width: 1,
    height: 3,
    maxStack: 1,
    weight: 2.2,
    tags: ['weapon'],
    sprite: 'item.pipe',
    use: null,
    melee: WEAPONS.pipe,
    noise: 200,
    throwable: true,
    charge: 0,
  }),
  'item.wrench': item({
    id: 'item.wrench',
    nameKey: 'item.item.wrench.name',
    descriptionKey: 'item.item.wrench.desc',
    width: 1,
    height: 2,
    maxStack: 1,
    weight: 1.4,
    tags: ['weapon'],
    sprite: 'item.wrench',
    use: null,
    melee: WEAPONS.wrench,
    noise: 170,
    throwable: true,
    charge: 0,
  }),
  'item.noisemaker': item({
    id: 'item.noisemaker',
    nameKey: 'item.item.noisemaker.name',
    descriptionKey: 'item.item.noisemaker.desc',
    width: 1,
    height: 1,
    maxStack: 3,
    weight: 0.4,
    tags: ['lure'],
    sprite: 'item.noisemaker',
    use: null,
    melee: null,
    noise: 460,
    throwable: true,
    charge: 0,
  }),
};
